version: "2.2"

services:
  mysql:
    image: mysql:8.2
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
    volumes:
      - "/var/mysql:/var/lib/mysql"
    profiles:
      - mysql

  postgres:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - POSTGRES_DB=
    profiles:
      - postgres
