version: '2.2'

services:
  petclinic:
    image: petclinic_app_image
    ports:
      -"8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.2
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=mysql
    volumes:
      - "/var/mysql:/var/lib/mysql"
    profiles:
      - mysql
    